apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: kw-build-pipeline-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: build-mvn-jib
  params:
  - name: revision
    value: main
  - name: insecure-registry
    value: "true"
  - name: git-url
    value: http://gitea.gitea:3000/argo/kw-mvn.git
  - name: image-url
    value: "10.214.156.101:30005/kw-mvn"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-build
  - name: gitops
    emptyDir: {}
