---
apiVersion: v1
kind: Namespace
metadata:
  name: code-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: code-server
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: code:test
        imagePullPolicy: IfNotPresent
        env:
          - name: TZ
            value: Asia/Seoul
          - name: PASSWORD
            value: "1"
---
apiVersion: v1
kind: Service
metadata:
  namespace: code-server
  name: code-server
  labels:
    app: code-server
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: web
  type: ClusterIP
  selector:
    app: code-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server
  namespace: code-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: "code.kw02"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 8080
