---
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: k8s-rbac
subjects:
  - kind: ServiceAccount
    name: default
    namespace: dev
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
  namespace: dev
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: dev
spec:
  selector:
    matchLabels:
      app: dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
      - name: dev
        image: docker.kubeworks.net/kw-dev:v1
        imagePullPolicy: IfNotPresent
        stdin: true
        tty: true
        env:
          - name: TZ
            value: Asia/Seoul
        volumeMounts:
        - name: dev-volume
          mountPath: /root/works
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
      volumes:
        - name: dev-volume
          persistentVolumeClaim:
            claimName: dev-pvc
        - name: docker-sock-volume
          hostPath:
            path: /var/run/docker.sock
            type: Socket
