---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: nexus-ca
    cert-manager.io/issuer-kind: Issuer
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  name: docker
  namespace: nexus  
spec:
  rules:
  - host: docker.kubeworks.net
    http:
      paths:
      - backend:
          serviceName: nexus-nexus-repository-manager
          servicePort: 5000
  tls:
  - hosts:
    - docker.kubeworks.net
    secretName: tls-docker-kubeworks-ingress
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nexus-ca
  namespace: nexus
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nexus-ca
  namespace: nexus
spec:
  isCA: true
  secretName: nexus-ca
  commonName: nexus ca
  issuerRef:
    name: nexus-ca
    kind: Issuer
