apiVersion: v1
kind: List
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: kw-mvn-helm
    namespace: argocd
  spec:
    destination:
      namespace: deploy-helm
      server: https://kubernetes.default.svc
    project: default
    source:
      chart: kw-mvn
      helm:
        parameters:
        - name: service.nodeport
          value: "30090"
      repoURL: https://flytux.github.io/kw-mvn-deploy/
      targetRevision: 0.1.0
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: kw-mvn-kust-base
    namespace: argocd
  spec:
    destination:
      namespace: deploy-kust-base
      server: https://kubernetes.default.svc
    project: default
    source:
      path: base
      repoURL: https://github.com/flytux/kw-mvn-deploy.git
      targetRevision: kust
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: kw-mvn-kust-dev
    namespace: argocd
  spec:
    destination:
      namespace: deploy-kust-dev
      server: https://kubernetes.default.svc
    project: default
    source:
      path: dev
      repoURL: https://github.com/flytux/kw-mvn-deploy.git
      targetRevision: kust
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    name: kw-mvn-yaml
    namespace: argocd
  spec:
    destination:
      namespace: deploy-yaml
      server: https://kubernetes.default.svc
    project: default
    source:
      directory:
        jsonnet: {}
        recurse: true
      path: .
      repoURL: https://github.com/flytux/kw-mvn-deploy.git
      targetRevision: yaml
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
