apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kw-mvn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default # You may need to change this!
  source:
    path: ./
    repoURL: http://gitea.gitea:3000/tekton/kw-mvn-deploy.git
    targetRevision: main

  destination:
    server: https://kubernetes.default.svc
    namespace: deploy
  syncPolicy:
    ## https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
