apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton
spec:
  ingressClassName: nginx
  rules:
  - host: tekton.kw01
    http:
      paths:
      - backend:
          service:
            name: tekton-dashboard
            port:
              number: 80
        pathType: ImplementationSpecific
