apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spring-boot-actuator-monitor
  namespace: deploy
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: http-port
  namespaceSelector:
    matchNames:
    - deploy
  selector:
    matchLabels:
      stage: dev
