---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jib
  namespace: build
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
